"""Curated issuer/devedor canonicalization tables.

Ported verbatim from `templates/controlpanel.html` (`_BANK_CANONICALS` /
`_DEVEDOR_CANONICALS`, ~templates/controlpanel.html:3431-3701) via
`scripts/port_canonicals.py` at registration-rules build time -- both this file and the JS tables are the
SAME curated data (no separate JSON source survives, per
`reference/beehusName-regra-final.md` §3). Keep them in sync by re-running
the port script after editing the JS tables, or vice-versa; do not hand-edit
one without the other drifting.
"""

BANK_CANONICALS = [
    ('Banco C6', ['BANCO C6 CONSIGNADO S.A.', 'BANCO C6 CONSIGNADO', 'BANCO C6 PRÉ', 'BANCO C6 PÓS', 'BANCO C6', 'C6 BANK', 'C6']),
    ('Bradesco', ['BANCO BRADESCO S.A.', 'BANCO BRADESCO', 'BRADESCO']),
    ('BTG Pactual', ['BANCO BTG PACTUAL S.A', 'BANCO BTG PACTUAL SA', 'BANCO BTG PACTUAL', 'BTG PACTUAL']),
    ('Itaú', ['ITAU', 'ITAÚ']),
    ('BMG', ['BANCO BMG S.A', 'BANCO BMG', 'BMG']),
    ('Pine', ['BANCO PINE', 'PINE']),
    ('Caixa Econômica', ['CAIXA ECONOMICA', 'CAIXA ECONÔMICA']),
    ('Safra', ['BANCO SAFRA', 'SAFRA']),
    ('Original', ['BANCO ORIGINAL S/A', 'BANCO ORIGINAL', 'ORIGINAL']),
    ('BNDES', ['BNDES']),
    ('XP', ['BANCO XP S.A.', 'BANCO XP', 'XP']),
    ('Pan', ['BANCO PAN S/A', 'BANCO PAN', 'PAN']),
    ('Banco ABC', ['BANCO ABC', 'ABC']),
    ('Santander', ['BANCO SANTANDER', 'SANTANDER']),
    ('Itauvest', ['ITAUVEST', 'ITAÚVEST']),
    ('Bocom BBM', ['BANCO BOCOM BBM SA', 'BANCO BOCOM BBM', 'BOCOM BBM']),
    ('Agibank', ['BANCO AGIBANK S.A', 'BANCO AGIBANK', 'AGIBANK']),
    ('Digimais', ['BANCO DIGIMAIS', 'DIGIMAIS']),
    ('Rabobank', ['BANCO RABOBANK', 'RABOBANK']),
    ('Daycoval', ['BANCO DAYCOVAL', 'DAYCOVAL']),
    ('Will Financeira', ['WILL FINANCEIRA']),
    ('Fibra', ['BANCO FIBRA SA', 'BANCO FIBRA', 'FIBRA']),
    ('Automatico Safra', ['AUTOMÁTICO SAFRA', 'AUTOMATICO SAFRA']),
    ('Picpay', ['PICPAY']),
    ('Itaú Unibanco S.A.', ['ITAÚ UNIBANCO S.A.', 'ITAU UNIBANCO']),
    ('Banco Master', ['BANCO MASTER S/A', 'BANCO MASTER', 'MASTER']),
    ('CEF', ['CEF']),
    ('Banco Votorantim', ['BANCO VOTORANTIM', 'VOTORANTIM']),
    ('BV', ['BANCO BV S/A', 'BANCO BV', 'BV S.A', 'BV']),
    ('BS2', ['BANCO BS2', 'BS2']),
    ('Pleno', ['BANCO PLENO SA', 'PLENO']),
    ('BRB', ['BRB']),
    ('Neon Financeira', ['NEON FINANCEIRA']),
    ('Facta', ['FACTA']),
    ('Sicoob', ['SICOOB']),
    ('NBC', ['NBC']),
    ('Banco do Brasil', ['BANCO DO BRASIL']),
    ('John Deere', ['BANCO JOHN DEERE S.A.', 'BANCO JOHN DEERE', 'JOHN DEERE']),
    ('Stellantis', ['STELLANTIS']),
    ('Banco ABC Brasil', ['BANCO ABC BRASIL']),
    ('Andbank', ['BANCO ANDBANK', 'ANDBANK']),
    ('CNH', ['BANCO CNH', 'CNH']),
    ('Luso Brasileiro', ['BANCO LUSO BRASILEIRO S.A', 'LUSO BRASILEIRO']),
    ('Sicredi', ['BANCO SICREDI', 'SICREDI']),
    ('Banco BBM', ['BANCO BBM', 'BBM']),
    ('Caruana', ['CARUANA S/A', 'CARUANA']),
    ('Inter', ['BANCO INTER S/A', 'BANCO INTER', 'INTER']),
    ('Afinz', ['BANCO AFINZ SA', 'AFINZ']),
    ('DM Financeira', ['DM FINANCEIRA']),
    ('Midway', ['MIDWAY']),
    ('Pernambucanas', ['PERNAMBUCANAS']),
    ('BRDE', ['BANCO BRDE', 'BRDE']),
    ('Banco Bocom', ['BANCO BOCOM', 'BOCOM']),
    ('Banco Cooperativo Sicoob', ['BANCO COOPERATIVO SICOOB']),
    ('Caixa Economica Federal', ['CAIXA ECONOMICA FEDERAL']),
    ('Omni Financeira', ['OMNI FINANCEIRA']),
    ('Rodobens', ['RODOBENS']),
    ('Caixa', ['CAIXA']),
    ('Paulista', ['BANCO PAULISTA', 'PAULISTA']),
    ('Senff', ['SENFF']),
    ('BRP', ['BRP']),
    ('Banco Agibank Pós', ['BANCO AGIBANK PÓS']),
    ('Banco CNH Capital', ['BANCO CNH CAPITAL', 'CNH CAPITAL']),
    ('Banco CNH Industrial Capital', ['BANCO CNH INDUSTRIAL CAPITAL']),
    ('Banco Votorantim Pré', ['BANCO VOTORANTIM PRÉ']),
    ('CCB', ['CCB']),
    ('Facta Financeira', ['FACTA FINANCEIRA']),
    ('Haitong', ['HAITONG']),
    ('Nubank', ['BANCO NUBANK', 'NUBANK']),
    ('Poupex', ['POUPEX']),
    ('Socinal', ['SOCINAL']),
    ('BDMG', ['BANCO BDMG', 'BDMG']),
    ('BR Partners', ['BR PARTNERS']),
    ('BRB Banco de Brasilia', ['BRB BANCO DE BRASILIA SA', 'BRB BANCO DE BRASILIA']),
    ('Banco Afinz Pós', ['BANCO AFINZ PÓS']),
    ('Banco Paraná', ['BANCO PARANA', 'BANCO PARANÁ']),
    ('Banco Rendimento', ['BANCO RENDIMENTO', 'RENDIMENTO']),
    ('DLL', ['BANCO DLL', 'DLL']),
    ('Emissão Safra', ['EMISSÃO SAFRA']),
    ('Engelhart', ['ENGELHART']),
    ('Mercantil', ['MERCANTIL']),
    ('NU - Teste', ['NU - TESTE']),
    ('Neon Pós', ['NEON PÓS']),
    ('Omni', ['OMNI']),
    ('Omni Pós', ['OMNI PÓS']),
    ('Pré', ['PRÉ']),
    ('RP Financeira', ['RP FINANCEIRA']),
    ('Sicredi Invest', ['SICREDI INVEST']),
    ('Will', ['WILL']),
    ('XCMG Brasil', ['BANCO XCMG BRASIL S/A', 'XCMG BRASIL']),
    ('- Banco Bradesco', ['- BANCO BRADESCO']),
    ('Agrolend', ['AGROLEND']),
    ('Alfa Investimento', ['ALFA INVESTIMENTO']),
    ('BTG', ['BTG']),
    ('Banco ABC Brasil Pré', ['BANCO ABC BRASIL PRÉ']),
    ('Banco Andbank (Brasil) S/A', ['BANCO ANDBANK (BRASIL) S/A', 'BANCO ANDBANK (BRASIL)']),
    ('Banco Andbank Pós', ['BANCO ANDBANK PÓS']),
    ('Banco BMG Pré', ['BANCO BMG PRÉ']),
    ('Banco BMG Pós', ['BANCO BMG PÓS']),
    ('Banco Cooperativo Sicredi Pré', ['BANCO COOPERATIVO SICREDI PRÉ']),
    ('Banco Digimais Pós', ['BANCO DIGIMAIS PÓS']),
    ('Banco Mercantil Pós', ['BANCO MERCANTIL PÓS']),
    ('Banco Original Pós', ['BANCO ORIGINAL PÓS']),
    ('Banco Santander Pré', ['BANCO SANTANDER PRÉ']),
    ('Bank Of China', ['BANK OF CHINA']),
    ('Bocon BBM', ['BOCON BBM']),
    ('Concorbc', ['CONCORBC']),
    ('Caixa Economica Federal Pré', ['CAIXA ECONOMICA FEDERAL PRÉ']),
    ('Caruana Pós', ['CARUANA PÓS']),
    ('Crediare', ['CREDIARE']),
    ('Dcls', ['DCLS']),
    ('Genial', ['GENIAL']),
    ('Icbc', ['ICBC']),
    ('Intermedium', ['INTERMEDIUM']),
    ('Lebes Financeira', ['LEBES FINANCEIRA']),
    ('Novo Banco Continental', ['NOVO BANCO CONTINENTAL']),
    ('Novo Banco Continetal Pós', ['NOVO BANCO CONTINETAL PÓS']),
    ('Omni Banco S/A', ['OMNI BANCO S/A', 'OMNI BANCO']),
    ('Ouribank', ['OURIBANK']),
    ('Pernambucanas Financiadora', ['PERNAMBUCANAS FINANCIADORA']),
    ('Semear', ['SEMEAR']),
    ('Sorocred', ['SOROCRED']),
    ('BB', ['BANCO DO BRASIL']),
    ('BNB', ['BANCO DO NORDESTE DO BRASIL S.A.', 'BANCO DO NORDESTE', 'BNB']),
    ('Banestes', ['BANCO BANESTES S.A.', 'BANCO BANESTES', 'BANESTES']),
    ('CNH Capital', ['BANCO CNH CAPITAL S/A', 'BANCO CNH CAPITAL', 'CNH CAPITAL']),
    ('Industrial', ['BANCO INDUSTRIAL DO BRASIL S.A.', 'BANCO INDUSTRIAL DO BRASIL']),
    ('Rendimento', ['BANCO RENDIMENTO S.A.', 'BANCO RENDIMENTO']),
    ('Sofisa', ['BANCO SOFISA S.A.', 'BANCO SOFISA', 'SOFISA']),
    ('Triângulo', ['BANCO TRIANGULO S/A', 'BANCO TRIANGULO', 'TRIANGULO']),
]

DEVEDOR_CANONICALS = [
    ("Rede D'Or", ["REDE D'OR", 'REDE DOR']),
    ('Minerva', ['MINERVA']),
    ('Marfrig', ['MARFRIG']),
    ('BTG', ['BTG']),
    ('Klabin', ['KLABIN']),
    ('Raizen', ['RAIZEN', 'RAÍZEN']),
    ('JBS', ['JBS']),
    ('JSL', ['JSL']),
    ('BRF', ['BRF']),
    ('Direcional', ['DIRECIONAL']),
    ('Ipiranga', ['IPIRANGA']),
    ('Raia Drogasil', ['RAIA DROGASIL']),
    ('Riza Securitizadora', ['RIZA SECURITIZADORA']),
    ('Vamos', ['VAMOS']),
    ('Camil', ['CAMIL']),
    ('Dasa', ['DASA']),
    ('Localiza', ['LOCALIZA']),
    ('MRV', ['MRV']),
    ('Brookfield', ['BROOKFIELD']),
    ('Cyrela', ['CYRELA']),
    ('Opea Securitizadora', ['OPEA SECURITIZADORA S/A', 'OPEA SECURITIZADORA S.A', 'OPEA SECURITIZADORA']),
    ('Fs Bio', ['FS BIO']),
    ('GPA', ['GPA']),
    ('Movida', ['MOVIDA']),
    ('Opea', ['OPEA']),
    ('Petrobras', ['PETROBRAS']),
    ('Iguatemi', ['IGUATEMI']),
    ('Light', ['LIGHT']),
    ('Seara', ['SEARA']),
    ('Vibra Energia S.A.', ['VIBRA ENERGIA S.A']),
    ('Assai', ['ASSAI', 'ASSAÍ']),
    ('Atacadão', ['ATACADÃO', 'ATACADAO']),
    ('Barretos', ['BARRETOS']),
    ('Dexco', ['DEXCO']),
    ('Multiplan', ['MULTIPLAN']),
    ('Petrobras', ['PETRÓLEO BRASILEIRO S.A']),
    ('SLC', ['SLC']),
    ('Allos', ['ALLOS SA', 'ALLOS']),
    ('Automob', ['AUTOMOB']),
    ('BTG Commodities', ['BTG COMMODITIES']),
    ('BTG Pactual', ['BANCO BTG PACTUAL', 'BTG PACTUAL']),
    ('Copersucar', ['COPERSUCAR']),
    ('Cury', ['CURY']),
    ('Eco Securitizadora', ['ECO SECURITIZADORA']),
    ('Ecoagro', ['ECOAGRO']),
    ('Hapvida', ['HAPVIDA']),
    ('Jhsf', ['JHSF']),
    ('Oncoclinicas', ['ONCOCLINICAS', 'ONCOCLÍNICAS']),
    ('True Securitizadora', ['TRUE SECURITIZADORA']),
    ('Unidas', ['UNIDAS']),
    ('Albert Einstein', ['ALBERT EINSTEIN']),
    ('B3', ['B3']),
    ('BR Foods', ['BR FOODS']),
    ('Bild', ['BILD']),
    ('Bradesco', ['BRADESCO']),
    ('Braskem', ['BRASKEM']),
    ('BTG Log', ['BTG LOG']),
    ('Caramuru', ['CARAMURU']),
    ('Cashme', ['CASHME']),
    ('Cerradinho', ['CERRADINHO']),
    ('Cocal', ['COCAL']),
    ('Cogna', ['COGNA']),
    ('Cooxupé', ['COOXUPÉ', 'COOXUPE']),
    ('Eneva', ['ENEVA']),
    ('Faz. Boa Vista', ['FAZ. BOA VISTA']),
    ('Fibria', ['FIBRIA']),
    ('Hypera', ['HYPERA']),
    ('Jhsf Participações', ['JHSF PARTICIPAÇÕES']),
    ('Mercado Livre', ['MERCADO LIVRE']),
    ('Natura', ['NATURA']),
    ('Olfar', ['OLFAR']),
    ('Real Parque', ['REAL PARQUE']),
    ("Rede D'or", ["REDE D'OR SÃO LUIZ S.A"]),
    ('Rumo', ['RUMO']),
    ('Sabesp', ['SABESP']),
    ('Sendas', ['SENDAS']),
    ('Tramontina', ['TRAMONTINA']),
    ('Vert', ['VERT']),
    ('Virgo', ['VIRGO']),
    ('Votorantim Cimentos', ['VOTORANTIM CIMENTOS']),
    ('Aiz', ['AIZ']),
    ('Adecoagro Vale do Ivinhema', ['ADECOAGRO VALE DO IVINHEMA']),
    ('Agibank', ['AGIBANK']),
    ('Aliansce Sonae', ['ALIANSCE SONAE']),
    ('Almarias', ['ALMARIAS']),
    ('Açucareira', ['AÇUCAREIRA']),
    ('Bari Securitizadora', ['BARI SECURITIZADORA']),
    ('Barigui', ['BARIGUI']),
    ('Bewiki', ['BEWIKI']),
    ('Boa Nova', ['BOA NOVA']),
    ('BRagro', ['BRAGRO']),
    ('BrasilAgro', ['BRASILAGRO']),
    ('CF Alves Adm Imobiliária', ['CF ALVES ADM IMOBILIÁRIA']),
    ('CPFL Transmissao', ['CPFL TRANSMISSAO']),
    ('Cyrela Brazil Realty AS Empreend', ['CYRELA BRAZIL REALTY AS EMPREEND']),
    ('Energisa', ['ENERGISA']),
    ('Fs Florestal', ['FS FLORESTAL']),
    ('GDM', ['GDM']),
    ('GTFoods', ['GTFOODS']),
    ('GVI', ['GVI']),
    ('Gramado', ['GRAMADO']),
    ('Grupo JB', ['GRUPO JB']),
    ('Grupo Pão de Açucar', ['GRUPO PÃO DE AÇUCAR']),
    ('Irani', ['IRANI']),
    ('Itaú', ['ITAÚ']),
    ('Kallas', ['KALLAS']),
    ('MRV Flex', ['MRV FLEX']),
    ('Mateus Supermercados', ['MATEUS SUPERMERCADOS']),
    ('Nagro', ['NAGRO']),
    ('Neomille', ['NEOMILLE']),
    ('Nissei', ['NISSEI']),
    ('Pacaembu', ['PACAEMBU']),
    ('Parque dos Ingleses', ['PARQUE DOS INGLESES']),
    ('Patense', ['PATENSE']),
    ('Patrimar', ['PATRIMAR']),
    ('Piracanjuba', ['PIRACANJUBA']),
    ('Plano & Plano', ['PLANO & PLANO']),
    ('Planta', ['PLANTA']),
    ('Rumo Malha Paulista', ['RUMO MALHA PAULISTA']),
    ('Saneatins', ['SANEATINS']),
    ('Solfacil', ['SOLFACIL']),
    ('Stahel', ['STAHEL']),
    ('Taesa', ['TAESA']),
    ('Tanac', ['TANAC']),
    ('Tenda Atacado', ['TENDA ATACADO']),
    ('Tereos', ['TEREOS']),
    ('Tramontina', ['TRAMONTINA S.A CUTELARIA']),
    ('Trinity II', ['TRINITY II']),
    ('Trisul', ['TRISUL']),
    ('Unidas (Ouro Verde)', ['UNIDAS (OURO VERDE)']),
    ('Usiminas', ['USIMINAS']),
    ('Vale', ['VALE']),
    ('Vicunha', ['VICUNHA']),
    ('Virgo Companhia de Securitização', ['VIRGO COMPANHIA DE SECURITIZAÇÃO']),
    ('Yduqs', ['YDUQS']),
    ('Zamp', ['ZAMP']),
]
